"""empty message

Revision ID: 40066aba6a51
Revises: c9a13cb01d96
Create Date: 2022-09-13 15:09:39.403563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40066aba6a51'
down_revision = 'c9a13cb01d96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_history', sa.Column('time', sa.String(length=120), nullable=True))
    op.add_column('student_history', sa.Column('score', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_student_history_time'), 'student_history', ['time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_history_time'), table_name='student_history')
    op.drop_column('student_history', 'score')
    op.drop_column('student_history', 'time')
    # ### end Alembic commands ###
