"""users table

Revision ID: 428d0d4a90a9
Revises: 2dfbbce61771
Create Date: 2022-07-29 15:45:26.641507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '428d0d4a90a9'
down_revision = '2dfbbce61771'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_teacher', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_teacher')
    # ### end Alembic commands ###
