"""empty message

Revision ID: 6876763e1a97
Revises: 40066aba6a51
Create Date: 2022-09-14 12:54:50.400838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6876763e1a97'
down_revision = '40066aba6a51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_history', sa.Column('count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student_history', 'count')
    # ### end Alembic commands ###
