"""empty message

Revision ID: ebc4718e8cb3
Revises: e996722fd212
Create Date: 2022-08-25 01:51:35.964613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebc4718e8cb3'
down_revision = 'e996722fd212'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_answer_desc', table_name='answer')
    op.create_index(op.f('ix_answer_desc'), 'answer', ['desc'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_answer_desc'), table_name='answer')
    op.create_index('ix_answer_desc', 'answer', ['desc'], unique=False)
    # ### end Alembic commands ###
